spring:
  application:
    name: wis-admin-api
  cloud:
    azure:
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        key: ${AZURE_COSMOS_KEY}
        database: ${AZURE_COSMOS_DATABASE:WIS-Platform}

server:
  port: 8080

# CORS configuration for React frontend
cors:
  allowed-origins: http://localhost:3000,http://localhost:5173,https://admin.wordsinseasonapp.com
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.wis.admin: INFO
    com.azure.cosmos: WARN
